-- Adds an "instruments" table: every constituent of NSE's NIFTY 100,
-- NIFTY MIDCAP 150, NIFTY SMALLCAP 250, and NIFTY MICROCAP 250 indices, one
-- row per (ticker, index) pair. Independent of screener_universes (which
-- holds only the ~80-per-tier subset the screener actually scans, capped
-- for the 60s Vercel timeout) -- this is the full, uncapped reference list
-- for lookups elsewhere in the app (e.g. resolving a ticker's index/
-- company name on the Cost Basis page). Run once manually in Neon's SQL
-- Editor (or via psql), after 001-005.
--
-- Source: NSE's official index constituent CSVs (niftyindices.com/
-- IndexConstituent/ind_<index>list.csv), fetched 2026-09-04. No stock
-- appears in more than one of these four indices (they partition the
-- market-cap ranking by construction), so ticker alone is the primary
-- key -- re-running this script is safe via ON CONFLICT DO NOTHING, but
-- note it won't pick up index reconstitutions after this date; re-run
-- with fresh CSVs (or a DELETE + re-INSERT) when NSE rebalances.

CREATE TABLE IF NOT EXISTS instruments (
    ticker TEXT PRIMARY KEY,
    index_name TEXT NOT NULL,
    stock_name TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS instruments_index_name_idx ON instruments (index_name);

INSERT INTO instruments (ticker, index_name, stock_name) VALUES
    ('ABB', 'NIFTY 100', 'ABB India Ltd.'),
    ('ADANIENSOL', 'NIFTY 100', 'Adani Energy Solutions Ltd.'),
    ('ADANIENT', 'NIFTY 100', 'Adani Enterprises Ltd.'),
    ('ADANIGREEN', 'NIFTY 100', 'Adani Green Energy Ltd.'),
    ('ADANIPORTS', 'NIFTY 100', 'Adani Ports and Special Economic Zone Ltd.'),
    ('ADANIPOWER', 'NIFTY 100', 'Adani Power Ltd.'),
    ('AMBUJACEM', 'NIFTY 100', 'Ambuja Cements Ltd.'),
    ('APOLLOHOSP', 'NIFTY 100', 'Apollo Hospitals Enterprise Ltd.'),
    ('ASIANPAINT', 'NIFTY 100', 'Asian Paints Ltd.'),
    ('DMART', 'NIFTY 100', 'Avenue Supermarts Ltd.'),
    ('AXISBANK', 'NIFTY 100', 'Axis Bank Ltd.'),
    ('BAJAJ-AUTO', 'NIFTY 100', 'Bajaj Auto Ltd.'),
    ('BAJFINANCE', 'NIFTY 100', 'Bajaj Finance Ltd.'),
    ('BAJAJFINSV', 'NIFTY 100', 'Bajaj Finserv Ltd.'),
    ('BAJAJHLDNG', 'NIFTY 100', 'Bajaj Holdings & Investment Ltd.'),
    ('BANKBARODA', 'NIFTY 100', 'Bank of Baroda'),
    ('BEL', 'NIFTY 100', 'Bharat Electronics Ltd.'),
    ('BPCL', 'NIFTY 100', 'Bharat Petroleum Corporation Ltd.'),
    ('BHARTIARTL', 'NIFTY 100', 'Bharti Airtel Ltd.'),
    ('BOSCHLTD', 'NIFTY 100', 'Bosch Ltd.'),
    ('BRITANNIA', 'NIFTY 100', 'Britannia Industries Ltd.'),
    ('CGPOWER', 'NIFTY 100', 'CG Power and Industrial Solutions Ltd.'),
    ('CANBK', 'NIFTY 100', 'Canara Bank'),
    ('CHOLAFIN', 'NIFTY 100', 'Cholamandalam Investment and Finance Company Ltd.'),
    ('CIPLA', 'NIFTY 100', 'Cipla Ltd.'),
    ('COALINDIA', 'NIFTY 100', 'Coal India Ltd.'),
    ('CUMMINSIND', 'NIFTY 100', 'Cummins India Ltd.'),
    ('DLF', 'NIFTY 100', 'DLF Ltd.'),
    ('DIVISLAB', 'NIFTY 100', 'Divi''s Laboratories Ltd.'),
    ('DRREDDY', 'NIFTY 100', 'Dr. Reddy''s Laboratories Ltd.'),
    ('EICHERMOT', 'NIFTY 100', 'Eicher Motors Ltd.'),
    ('ETERNAL', 'NIFTY 100', 'Eternal Ltd.'),
    ('GAIL', 'NIFTY 100', 'GAIL (India) Ltd.'),
    ('GODREJCP', 'NIFTY 100', 'Godrej Consumer Products Ltd.'),
    ('GRASIM', 'NIFTY 100', 'Grasim Industries Ltd.'),
    ('HCLTECH', 'NIFTY 100', 'HCL Technologies Ltd.'),
    ('HDFCAMC', 'NIFTY 100', 'HDFC Asset Management Company Ltd.'),
    ('HDFCBANK', 'NIFTY 100', 'HDFC Bank Ltd.'),
    ('HDFCLIFE', 'NIFTY 100', 'HDFC Life Insurance Company Ltd.'),
    ('HINDALCO', 'NIFTY 100', 'Hindalco Industries Ltd.'),
    ('HAL', 'NIFTY 100', 'Hindustan Aeronautics Ltd.'),
    ('HINDUNILVR', 'NIFTY 100', 'Hindustan Unilever Ltd.'),
    ('HINDZINC', 'NIFTY 100', 'Hindustan Zinc Ltd.'),
    ('HYUNDAI', 'NIFTY 100', 'Hyundai Motor India Ltd.'),
    ('ICICIBANK', 'NIFTY 100', 'ICICI Bank Ltd.'),
    ('ITC', 'NIFTY 100', 'ITC Ltd.'),
    ('INDHOTEL', 'NIFTY 100', 'Indian Hotels Co. Ltd.'),
    ('IOC', 'NIFTY 100', 'Indian Oil Corporation Ltd.'),
    ('IRFC', 'NIFTY 100', 'Indian Railway Finance Corporation Ltd.'),
    ('INFY', 'NIFTY 100', 'Infosys Ltd.'),
    ('INDIGO', 'NIFTY 100', 'InterGlobe Aviation Ltd.'),
    ('JSWSTEEL', 'NIFTY 100', 'JSW Steel Ltd.'),
    ('JINDALSTEL', 'NIFTY 100', 'Jindal Steel Ltd.'),
    ('JIOFIN', 'NIFTY 100', 'Jio Financial Services Ltd.'),
    ('KOTAKBANK', 'NIFTY 100', 'Kotak Mahindra Bank Ltd.'),
    ('LTM', 'NIFTY 100', 'LTM Ltd.'),
    ('LT', 'NIFTY 100', 'Larsen & Toubro Ltd.'),
    ('LODHA', 'NIFTY 100', 'Lodha Developers Ltd.'),
    ('M&M', 'NIFTY 100', 'Mahindra & Mahindra Ltd.'),
    ('MARUTI', 'NIFTY 100', 'Maruti Suzuki India Ltd.'),
    ('MAXHEALTH', 'NIFTY 100', 'Max Healthcare Institute Ltd.'),
    ('MAZDOCK', 'NIFTY 100', 'Mazagoan Dock Shipbuilders Ltd.'),
    ('MUTHOOTFIN', 'NIFTY 100', 'Muthoot Finance Ltd.'),
    ('NTPC', 'NIFTY 100', 'NTPC Ltd.'),
    ('NESTLEIND', 'NIFTY 100', 'Nestle India Ltd.'),
    ('ONGC', 'NIFTY 100', 'Oil & Natural Gas Corporation Ltd.'),
    ('PIDILITIND', 'NIFTY 100', 'Pidilite Industries Ltd.'),
    ('PFC', 'NIFTY 100', 'Power Finance Corporation Ltd.'),
    ('POWERGRID', 'NIFTY 100', 'Power Grid Corporation of India Ltd.'),
    ('PNB', 'NIFTY 100', 'Punjab National Bank'),
    ('RECLTD', 'NIFTY 100', 'REC Ltd.'),
    ('RELIANCE', 'NIFTY 100', 'Reliance Industries Ltd.'),
    ('SBILIFE', 'NIFTY 100', 'SBI Life Insurance Company Ltd.'),
    ('MOTHERSON', 'NIFTY 100', 'Samvardhana Motherson International Ltd.'),
    ('SHREECEM', 'NIFTY 100', 'Shree Cement Ltd.'),
    ('SHRIRAMFIN', 'NIFTY 100', 'Shriram Finance Ltd.'),
    ('ENRIN', 'NIFTY 100', 'Siemens Energy India Ltd.'),
    ('SIEMENS', 'NIFTY 100', 'Siemens Ltd.'),
    ('SOLARINDS', 'NIFTY 100', 'Solar Industries India Ltd.'),
    ('SBIN', 'NIFTY 100', 'State Bank of India'),
    ('SUNPHARMA', 'NIFTY 100', 'Sun Pharmaceutical Industries Ltd.'),
    ('TVSMOTOR', 'NIFTY 100', 'TVS Motor Company Ltd.'),
    ('TATACAP', 'NIFTY 100', 'Tata Capital Ltd.'),
    ('TCS', 'NIFTY 100', 'Tata Consultancy Services Ltd.'),
    ('TATACONSUM', 'NIFTY 100', 'Tata Consumer Products Ltd.'),
    ('TMCV', 'NIFTY 100', 'Tata Motors Ltd.'),
    ('TMPV', 'NIFTY 100', 'Tata Motors Passenger Vehicles Ltd.'),
    ('TATAPOWER', 'NIFTY 100', 'Tata Power Co. Ltd.'),
    ('TATASTEEL', 'NIFTY 100', 'Tata Steel Ltd.'),
    ('TECHM', 'NIFTY 100', 'Tech Mahindra Ltd.'),
    ('TITAN', 'NIFTY 100', 'Titan Company Ltd.'),
    ('TORNTPHARM', 'NIFTY 100', 'Torrent Pharmaceuticals Ltd.'),
    ('TRENT', 'NIFTY 100', 'Trent Ltd.'),
    ('ULTRACEMCO', 'NIFTY 100', 'UltraTech Cement Ltd.'),
    ('UNIONBANK', 'NIFTY 100', 'Union Bank of India'),
    ('UNITDSPR', 'NIFTY 100', 'United Spirits Ltd.'),
    ('VBL', 'NIFTY 100', 'Varun Beverages Ltd.'),
    ('VEDL', 'NIFTY 100', 'Vedanta Ltd.'),
    ('WIPRO', 'NIFTY 100', 'Wipro Ltd.'),
    ('ZYDUSLIFE', 'NIFTY 100', 'Zydus Lifesciences Ltd.'),
    ('360ONE', 'NIFTY MIDCAP 150', '360 ONE WAM Ltd.'),
    ('3MINDIA', 'NIFTY MIDCAP 150', '3M India Ltd.'),
    ('ACC', 'NIFTY MIDCAP 150', 'ACC Ltd.'),
    ('AIAENG', 'NIFTY MIDCAP 150', 'AIA Engineering Ltd.'),
    ('APLAPOLLO', 'NIFTY MIDCAP 150', 'APL Apollo Tubes Ltd.'),
    ('AUBANK', 'NIFTY MIDCAP 150', 'AU Small Finance Bank Ltd.'),
    ('AWL', 'NIFTY MIDCAP 150', 'AWL Agri Business Ltd.'),
    ('ABBOTINDIA', 'NIFTY MIDCAP 150', 'Abbott India Ltd.'),
    ('ATGL', 'NIFTY MIDCAP 150', 'Adani Total Gas Ltd.'),
    ('ABCAPITAL', 'NIFTY MIDCAP 150', 'Aditya Birla Capital Ltd.'),
    ('AJANTPHARM', 'NIFTY MIDCAP 150', 'Ajanta Pharmaceuticals Ltd.'),
    ('ALKEM', 'NIFTY MIDCAP 150', 'Alkem Laboratories Ltd.'),
    ('ANTHEM', 'NIFTY MIDCAP 150', 'Anthem Biosciences Ltd.'),
    ('APARINDS', 'NIFTY MIDCAP 150', 'Apar Industries Ltd.'),
    ('APOLLOTYRE', 'NIFTY MIDCAP 150', 'Apollo Tyres Ltd.'),
    ('ASHOKLEY', 'NIFTY MIDCAP 150', 'Ashok Leyland Ltd.'),
    ('ASTRAL', 'NIFTY MIDCAP 150', 'Astral Ltd.'),
    ('AUROPHARMA', 'NIFTY MIDCAP 150', 'Aurobindo Pharma Ltd.'),
    ('AIIL', 'NIFTY MIDCAP 150', 'Authum Investment & Infrastructure Ltd.'),
    ('BSE', 'NIFTY MIDCAP 150', 'BSE Ltd.'),
    ('BAJAJHFL', 'NIFTY MIDCAP 150', 'Bajaj Housing Finance Ltd.'),
    ('BALKRISIND', 'NIFTY MIDCAP 150', 'Balkrishna Industries Ltd.'),
    ('BANKINDIA', 'NIFTY MIDCAP 150', 'Bank of India'),
    ('MAHABANK', 'NIFTY MIDCAP 150', 'Bank of Maharashtra'),
    ('BERGEPAINT', 'NIFTY MIDCAP 150', 'Berger Paints India Ltd.'),
    ('BDL', 'NIFTY MIDCAP 150', 'Bharat Dynamics Ltd.'),
    ('BHARATFORG', 'NIFTY MIDCAP 150', 'Bharat Forge Ltd.'),
    ('BHEL', 'NIFTY MIDCAP 150', 'Bharat Heavy Electricals Ltd.'),
    ('BHARTIHEXA', 'NIFTY MIDCAP 150', 'Bharti Hexacom Ltd.'),
    ('GROWW', 'NIFTY MIDCAP 150', 'Billionbrains Garage Ventures Ltd.'),
    ('BIOCON', 'NIFTY MIDCAP 150', 'Biocon Ltd.'),
    ('BLUESTARCO', 'NIFTY MIDCAP 150', 'Blue Star Ltd.'),
    ('CRISIL', 'NIFTY MIDCAP 150', 'CRISIL Ltd.'),
    ('COCHINSHIP', 'NIFTY MIDCAP 150', 'Cochin Shipyard Ltd.'),
    ('COFORGE', 'NIFTY MIDCAP 150', 'Coforge Ltd.'),
    ('COLPAL', 'NIFTY MIDCAP 150', 'Colgate Palmolive (India) Ltd.'),
    ('CONCOR', 'NIFTY MIDCAP 150', 'Container Corporation of India Ltd.'),
    ('COROMANDEL', 'NIFTY MIDCAP 150', 'Coromandel International Ltd.'),
    ('DABUR', 'NIFTY MIDCAP 150', 'Dabur India Ltd.'),
    ('DALBHARAT', 'NIFTY MIDCAP 150', 'Dalmia Bharat Ltd.'),
    ('DIXON', 'NIFTY MIDCAP 150', 'Dixon Technologies (India) Ltd.'),
    ('ENDURANCE', 'NIFTY MIDCAP 150', 'Endurance Technologies Ltd.'),
    ('ESCORTS', 'NIFTY MIDCAP 150', 'Escorts Kubota Ltd.'),
    ('EXIDEIND', 'NIFTY MIDCAP 150', 'Exide Industries Ltd.'),
    ('NYKAA', 'NIFTY MIDCAP 150', 'FSN E-Commerce Ventures Ltd.'),
    ('FEDERALBNK', 'NIFTY MIDCAP 150', 'Federal Bank Ltd.'),
    ('FORTIS', 'NIFTY MIDCAP 150', 'Fortis Healthcare Ltd.'),
    ('GVT&D', 'NIFTY MIDCAP 150', 'GE Vernova T&D India Ltd.'),
    ('GMRAIRPORT', 'NIFTY MIDCAP 150', 'GMR Airports Ltd.'),
    ('GICRE', 'NIFTY MIDCAP 150', 'General Insurance Corporation of India'),
    ('GLAXO', 'NIFTY MIDCAP 150', 'Glaxosmithkline Pharmaceuticals Ltd.'),
    ('GLENMARK', 'NIFTY MIDCAP 150', 'Glenmark Pharmaceuticals Ltd.'),
    ('MEDANTA', 'NIFTY MIDCAP 150', 'Global Health Ltd.'),
    ('GODFRYPHLP', 'NIFTY MIDCAP 150', 'Godfrey Phillips India Ltd.'),
    ('GODREJIND', 'NIFTY MIDCAP 150', 'Godrej Industries Ltd.'),
    ('GODREJPROP', 'NIFTY MIDCAP 150', 'Godrej Properties Ltd.'),
    ('FLUOROCHEM', 'NIFTY MIDCAP 150', 'Gujarat Fluorochemicals Ltd.'),
    ('HDBFS', 'NIFTY MIDCAP 150', 'HDB Financial Services Ltd.'),
    ('HAVELLS', 'NIFTY MIDCAP 150', 'Havells India Ltd.'),
    ('HEROMOTOCO', 'NIFTY MIDCAP 150', 'Hero MotoCorp Ltd.'),
    ('HEXT', 'NIFTY MIDCAP 150', 'Hexaware Technologies Ltd.'),
    ('HINDPETRO', 'NIFTY MIDCAP 150', 'Hindustan Petroleum Corporation Ltd.'),
    ('POWERINDIA', 'NIFTY MIDCAP 150', 'Hitachi Energy India Ltd.'),
    ('HONAUT', 'NIFTY MIDCAP 150', 'Honeywell Automation India Ltd.'),
    ('HUDCO', 'NIFTY MIDCAP 150', 'Housing & Urban Development Corporation Ltd.'),
    ('ICICIGI', 'NIFTY MIDCAP 150', 'ICICI Lombard General Insurance Company Ltd.'),
    ('ICICIAMC', 'NIFTY MIDCAP 150', 'ICICI Prudential Asset Management Company Ltd.'),
    ('ICICIPRULI', 'NIFTY MIDCAP 150', 'ICICI Prudential Life Insurance Company Ltd.'),
    ('IDFCFIRSTB', 'NIFTY MIDCAP 150', 'IDFC First Bank Ltd.'),
    ('ITCHOTELS', 'NIFTY MIDCAP 150', 'ITC Hotels Ltd.'),
    ('INDIANB', 'NIFTY MIDCAP 150', 'Indian Bank'),
    ('IRCTC', 'NIFTY MIDCAP 150', 'Indian Railway Catering And Tourism Corporation Ltd.'),
    ('IREDA', 'NIFTY MIDCAP 150', 'Indian Renewable Energy Development Agency Ltd.'),
    ('INDUSTOWER', 'NIFTY MIDCAP 150', 'Indus Towers Ltd.'),
    ('INDUSINDBK', 'NIFTY MIDCAP 150', 'IndusInd Bank Ltd.'),
    ('NAUKRI', 'NIFTY MIDCAP 150', 'Info Edge (India) Ltd.'),
    ('IPCALAB', 'NIFTY MIDCAP 150', 'Ipca Laboratories Ltd.'),
    ('JKCEMENT', 'NIFTY MIDCAP 150', 'J.K. Cement Ltd.'),
    ('JSWENERGY', 'NIFTY MIDCAP 150', 'JSW Energy Ltd.'),
    ('JSWINFRA', 'NIFTY MIDCAP 150', 'JSW Infrastructure Ltd.'),
    ('JSL', 'NIFTY MIDCAP 150', 'Jindal Stainless Ltd.'),
    ('JUBLFOOD', 'NIFTY MIDCAP 150', 'Jubilant Foodworks Ltd.'),
    ('KPRMILL', 'NIFTY MIDCAP 150', 'K.P.R. Mill Ltd.'),
    ('KEI', 'NIFTY MIDCAP 150', 'KEI Industries Ltd.'),
    ('KPITTECH', 'NIFTY MIDCAP 150', 'KPIT Technologies Ltd.'),
    ('KALYANKJIL', 'NIFTY MIDCAP 150', 'Kalyan Jewellers India Ltd.'),
    ('LTF', 'NIFTY MIDCAP 150', 'L&T Finance Ltd.'),
    ('LTTS', 'NIFTY MIDCAP 150', 'L&T Technology Services Ltd.'),
    ('LGEINDIA', 'NIFTY MIDCAP 150', 'LG Electronics India Ltd.'),
    ('LICHSGFIN', 'NIFTY MIDCAP 150', 'LIC Housing Finance Ltd.'),
    ('LAURUSLABS', 'NIFTY MIDCAP 150', 'Laurus Labs Ltd.'),
    ('LENSKART', 'NIFTY MIDCAP 150', 'Lenskart Solutions Ltd.'),
    ('LICI', 'NIFTY MIDCAP 150', 'Life Insurance Corporation of India'),
    ('LINDEINDIA', 'NIFTY MIDCAP 150', 'Linde India Ltd.'),
    ('LLOYDSME', 'NIFTY MIDCAP 150', 'Lloyds Metals And Energy Ltd.'),
    ('LUPIN', 'NIFTY MIDCAP 150', 'Lupin Ltd.'),
    ('MRF', 'NIFTY MIDCAP 150', 'MRF Ltd.'),
    ('M&MFIN', 'NIFTY MIDCAP 150', 'Mahindra & Mahindra Financial Services Ltd.'),
    ('MANKIND', 'NIFTY MIDCAP 150', 'Mankind Pharma Ltd.'),
    ('MARICO', 'NIFTY MIDCAP 150', 'Marico Ltd.'),
    ('MFSL', 'NIFTY MIDCAP 150', 'Max Financial Services Ltd.'),
    ('MOTILALOFS', 'NIFTY MIDCAP 150', 'Motilal Oswal Financial Services Ltd.'),
    ('MPHASIS', 'NIFTY MIDCAP 150', 'MphasiS Ltd.'),
    ('MCX', 'NIFTY MIDCAP 150', 'Multi Commodity Exchange of India Ltd.'),
    ('NHPC', 'NIFTY MIDCAP 150', 'NHPC Ltd.'),
    ('NLCINDIA', 'NIFTY MIDCAP 150', 'NLC India Ltd.'),
    ('NMDC', 'NIFTY MIDCAP 150', 'NMDC Ltd.'),
    ('NTPCGREEN', 'NIFTY MIDCAP 150', 'NTPC Green Energy Ltd.'),
    ('NATIONALUM', 'NIFTY MIDCAP 150', 'National Aluminium Co. Ltd.'),
    ('NAM-INDIA', 'NIFTY MIDCAP 150', 'Nippon Life India Asset Management Ltd.'),
    ('OBEROIRLTY', 'NIFTY MIDCAP 150', 'Oberoi Realty Ltd.'),
    ('OIL', 'NIFTY MIDCAP 150', 'Oil India Ltd.'),
    ('PAYTM', 'NIFTY MIDCAP 150', 'One 97 Communications Ltd.'),
    ('OFSS', 'NIFTY MIDCAP 150', 'Oracle Financial Services Software Ltd.'),
    ('POLICYBZR', 'NIFTY MIDCAP 150', 'PB Fintech Ltd.'),
    ('PIIND', 'NIFTY MIDCAP 150', 'PI Industries Ltd.'),
    ('PAGEIND', 'NIFTY MIDCAP 150', 'Page Industries Ltd.'),
    ('PATANJALI', 'NIFTY MIDCAP 150', 'Patanjali Foods Ltd.'),
    ('PERSISTENT', 'NIFTY MIDCAP 150', 'Persistent Systems Ltd.'),
    ('PETRONET', 'NIFTY MIDCAP 150', 'Petronet LNG Ltd.'),
    ('PHOENIXLTD', 'NIFTY MIDCAP 150', 'Phoenix Mills Ltd.'),
    ('POLYCAB', 'NIFTY MIDCAP 150', 'Polycab India Ltd.'),
    ('PREMIERENE', 'NIFTY MIDCAP 150', 'Premier Energies Ltd.'),
    ('PRESTIGE', 'NIFTY MIDCAP 150', 'Prestige Estates Projects Ltd.'),
    ('RADICO', 'NIFTY MIDCAP 150', 'Radico Khaitan Ltd'),
    ('RVNL', 'NIFTY MIDCAP 150', 'Rail Vikas Nigam Ltd.'),
    ('SBICARD', 'NIFTY MIDCAP 150', 'SBI Cards and Payment Services Ltd.'),
    ('SJVN', 'NIFTY MIDCAP 150', 'SJVN Ltd.'),
    ('SRF', 'NIFTY MIDCAP 150', 'SRF Ltd.'),
    ('SCHAEFFLER', 'NIFTY MIDCAP 150', 'Schaeffler India Ltd.'),
    ('SAIL', 'NIFTY MIDCAP 150', 'Steel Authority of India Ltd.'),
    ('SUNDARMFIN', 'NIFTY MIDCAP 150', 'Sundaram Finance Ltd.'),
    ('SUPREMEIND', 'NIFTY MIDCAP 150', 'Supreme Industries Ltd.'),
    ('SUZLON', 'NIFTY MIDCAP 150', 'Suzlon Energy Ltd.'),
    ('SWIGGY', 'NIFTY MIDCAP 150', 'Swiggy Ltd.'),
    ('TATACOMM', 'NIFTY MIDCAP 150', 'Tata Communications Ltd.'),
    ('TATAELXSI', 'NIFTY MIDCAP 150', 'Tata Elxsi Ltd.'),
    ('TATAINVEST', 'NIFTY MIDCAP 150', 'Tata Investment Corporation Ltd.'),
    ('NIACL', 'NIFTY MIDCAP 150', 'The New India Assurance Company Ltd.'),
    ('THERMAX', 'NIFTY MIDCAP 150', 'Thermax Ltd.'),
    ('TORNTPOWER', 'NIFTY MIDCAP 150', 'Torrent Power Ltd.'),
    ('TIINDIA', 'NIFTY MIDCAP 150', 'Tube Investments of India Ltd.'),
    ('UNOMINDA', 'NIFTY MIDCAP 150', 'UNO Minda Ltd.'),
    ('UPL', 'NIFTY MIDCAP 150', 'UPL Ltd.'),
    ('UBL', 'NIFTY MIDCAP 150', 'United Breweries Ltd.'),
    ('VMM', 'NIFTY MIDCAP 150', 'Vishal Mega Mart Ltd.'),
    ('IDEA', 'NIFTY MIDCAP 150', 'Vodafone Idea Ltd.'),
    ('VOLTAS', 'NIFTY MIDCAP 150', 'Voltas Ltd.'),
    ('WAAREEENER', 'NIFTY MIDCAP 150', 'Waaree Energies Ltd.'),
    ('YESBANK', 'NIFTY MIDCAP 150', 'Yes Bank Ltd.'),
    ('ACMESOLAR', 'NIFTY SMALLCAP 250', 'ACME Solar Holdings Ltd.'),
    ('AADHARHFC', 'NIFTY SMALLCAP 250', 'Aadhar Housing Finance Ltd.'),
    ('AARTIIND', 'NIFTY SMALLCAP 250', 'Aarti Industries Ltd.'),
    ('AAVAS', 'NIFTY SMALLCAP 250', 'Aavas Financiers Ltd.'),
    ('ACE', 'NIFTY SMALLCAP 250', 'Action Construction Equipment Ltd.'),
    ('ACUTAAS', 'NIFTY SMALLCAP 250', 'Acutaas Chemicals Ltd.'),
    ('ABFRL', 'NIFTY SMALLCAP 250', 'Aditya Birla Fashion and Retail Ltd.'),
    ('ABLBL', 'NIFTY SMALLCAP 250', 'Aditya Birla Lifestyle Brands Ltd.'),
    ('ABREL', 'NIFTY SMALLCAP 250', 'Aditya Birla Real Estate Ltd.'),
    ('ABSLAMC', 'NIFTY SMALLCAP 250', 'Aditya Birla Sun Life AMC Ltd.'),
    ('CPPLUS', 'NIFTY SMALLCAP 250', 'Aditya Infotech Ltd.'),
    ('AEGISLOG', 'NIFTY SMALLCAP 250', 'Aegis Logistics Ltd.'),
    ('AEGISVOPAK', 'NIFTY SMALLCAP 250', 'Aegis Vopak Terminals Ltd.'),
    ('AFCONS', 'NIFTY SMALLCAP 250', 'Afcons Infrastructure Ltd.'),
    ('AFFLE', 'NIFTY SMALLCAP 250', 'Affle 3i Ltd.'),
    ('ABDL', 'NIFTY SMALLCAP 250', 'Allied Blenders and Distillers Ltd.'),
    ('ARE&M', 'NIFTY SMALLCAP 250', 'Amara Raja Energy & Mobility Ltd.'),
    ('AMBER', 'NIFTY SMALLCAP 250', 'Amber Enterprises India Ltd.'),
    ('ANANDRATHI', 'NIFTY SMALLCAP 250', 'Anand Rathi Wealth Ltd.'),
    ('ANANTRAJ', 'NIFTY SMALLCAP 250', 'Anant Raj Ltd.'),
    ('ANGELONE', 'NIFTY SMALLCAP 250', 'Angel One Ltd.'),
    ('ANURAS', 'NIFTY SMALLCAP 250', 'Anupam Rasayan India Ltd.'),
    ('APTUS', 'NIFTY SMALLCAP 250', 'Aptus Value Housing Finance India Ltd.'),
    ('ASAHIINDIA', 'NIFTY SMALLCAP 250', 'Asahi India Glass Ltd.'),
    ('ASTERDM', 'NIFTY SMALLCAP 250', 'Aster DM Quality Care Ltd.'),
    ('ATHERENERG', 'NIFTY SMALLCAP 250', 'Ather Energy Ltd.'),
    ('ATUL', 'NIFTY SMALLCAP 250', 'Atul Ltd.'),
    ('BEML', 'NIFTY SMALLCAP 250', 'BEML Ltd.'),
    ('BLS', 'NIFTY SMALLCAP 250', 'BLS International Services Ltd.'),
    ('BALRAMCHIN', 'NIFTY SMALLCAP 250', 'Balrampur Chini Mills Ltd.'),
    ('BANDHANBNK', 'NIFTY SMALLCAP 250', 'Bandhan Bank Ltd.'),
    ('BATAINDIA', 'NIFTY SMALLCAP 250', 'Bata India Ltd.'),
    ('BAYERCROP', 'NIFTY SMALLCAP 250', 'Bayer Cropscience Ltd.'),
    ('BELRISE', 'NIFTY SMALLCAP 250', 'Belrise Industries Ltd.'),
    ('BIKAJI', 'NIFTY SMALLCAP 250', 'Bikaji Foods International Ltd.'),
    ('BSOFT', 'NIFTY SMALLCAP 250', 'Birlasoft Ltd.'),
    ('BLUEDART', 'NIFTY SMALLCAP 250', 'Blue Dart Express Ltd.'),
    ('BLUEJET', 'NIFTY SMALLCAP 250', 'Blue Jet Healthcare Ltd.'),
    ('BBTC', 'NIFTY SMALLCAP 250', 'Bombay Burmah Trading Corporation Ltd.'),
    ('FIRSTCRY', 'NIFTY SMALLCAP 250', 'Brainbees Solutions Ltd.'),
    ('BRIGADE', 'NIFTY SMALLCAP 250', 'Brigade Enterprises Ltd.'),
    ('MAPMYINDIA', 'NIFTY SMALLCAP 250', 'C.E. Info Systems Ltd.'),
    ('CCL', 'NIFTY SMALLCAP 250', 'CCL Products (I) Ltd.'),
    ('CESC', 'NIFTY SMALLCAP 250', 'CESC Ltd.'),
    ('CIEINDIA', 'NIFTY SMALLCAP 250', 'CIE Automotive India Ltd.'),
    ('CANFINHOME', 'NIFTY SMALLCAP 250', 'Can Fin Homes Ltd.'),
    ('CANHLIFE', 'NIFTY SMALLCAP 250', 'Canara HSBC Life Insurance Company Ltd.'),
    ('CAPLIPOINT', 'NIFTY SMALLCAP 250', 'Caplin Point Laboratories Ltd.'),
    ('CGCL', 'NIFTY SMALLCAP 250', 'Capri Global Capital Ltd.'),
    ('CARBORUNIV', 'NIFTY SMALLCAP 250', 'Carborundum Universal Ltd.'),
    ('CARTRADE', 'NIFTY SMALLCAP 250', 'Cartrade Tech Ltd.'),
    ('CASTROLIND', 'NIFTY SMALLCAP 250', 'Castrol India Ltd.'),
    ('CEATLTD', 'NIFTY SMALLCAP 250', 'Ceat Ltd.'),
    ('CEMPRO', 'NIFTY SMALLCAP 250', 'Cemindia Projects Ltd.'),
    ('CENTRALBK', 'NIFTY SMALLCAP 250', 'Central Bank of India'),
    ('CDSL', 'NIFTY SMALLCAP 250', 'Central Depository Services (India) Ltd.'),
    ('CHALET', 'NIFTY SMALLCAP 250', 'Chalet Hotels Ltd.'),
    ('CHAMBLFERT', 'NIFTY SMALLCAP 250', 'Chambal Fertilizers & Chemicals Ltd.'),
    ('CHENNPETRO', 'NIFTY SMALLCAP 250', 'Chennai Petroleum Corporation Ltd.'),
    ('CHOICEIN', 'NIFTY SMALLCAP 250', 'Choice International Ltd.'),
    ('CHOLAHLDNG', 'NIFTY SMALLCAP 250', 'Cholamandalam Financial Holdings Ltd.'),
    ('CUB', 'NIFTY SMALLCAP 250', 'City Union Bank Ltd.'),
    ('CLEAN', 'NIFTY SMALLCAP 250', 'Clean Science and Technology Ltd.'),
    ('COHANCE', 'NIFTY SMALLCAP 250', 'Cohance Lifesciences Ltd.'),
    ('CAMS', 'NIFTY SMALLCAP 250', 'Computer Age Management Services Ltd.'),
    ('CONCORDBIO', 'NIFTY SMALLCAP 250', 'Concord Biotech Ltd.'),
    ('CRAFTSMAN', 'NIFTY SMALLCAP 250', 'Craftsman Automation Ltd.'),
    ('CREDITACC', 'NIFTY SMALLCAP 250', 'CreditAccess Grameen Ltd.'),
    ('CROMPTON', 'NIFTY SMALLCAP 250', 'Crompton Greaves Consumer Electricals Ltd.'),
    ('CYIENT', 'NIFTY SMALLCAP 250', 'Cyient Ltd.'),
    ('DCMSHRIRAM', 'NIFTY SMALLCAP 250', 'DCM Shriram Ltd.'),
    ('DOMS', 'NIFTY SMALLCAP 250', 'DOMS Industries Ltd.'),
    ('DATAPATTNS', 'NIFTY SMALLCAP 250', 'Data Patterns (India) Ltd.'),
    ('DEEPAKFERT', 'NIFTY SMALLCAP 250', 'Deepak Fertilisers & Petrochemicals Corp. Ltd.'),
    ('DEEPAKNTR', 'NIFTY SMALLCAP 250', 'Deepak Nitrite Ltd.'),
    ('DELHIVERY', 'NIFTY SMALLCAP 250', 'Delhivery Ltd.'),
    ('DEVYANI', 'NIFTY SMALLCAP 250', 'Devyani International Ltd.'),
    ('LALPATHLAB', 'NIFTY SMALLCAP 250', 'Dr. Lal Path Labs Ltd.'),
    ('EIDPARRY', 'NIFTY SMALLCAP 250', 'E.I.D. Parry (India) Ltd.'),
    ('EIHOTEL', 'NIFTY SMALLCAP 250', 'EIH Ltd.'),
    ('ELECON', 'NIFTY SMALLCAP 250', 'Elecon Engineering Co. Ltd.'),
    ('ELGIEQUIP', 'NIFTY SMALLCAP 250', 'Elgi Equipments Ltd.'),
    ('EMAMILTD', 'NIFTY SMALLCAP 250', 'Emami Ltd.'),
    ('EMCURE', 'NIFTY SMALLCAP 250', 'Emcure Pharmaceuticals Ltd.'),
    ('EMMVEE', 'NIFTY SMALLCAP 250', 'Emmvee Photovoltaic Power Ltd.'),
    ('ENGINERSIN', 'NIFTY SMALLCAP 250', 'Engineers India Ltd.'),
    ('ERIS', 'NIFTY SMALLCAP 250', 'Eris Lifesciences Ltd.'),
    ('FACT', 'NIFTY SMALLCAP 250', 'Fertilisers and Chemicals Travancore Ltd.'),
    ('FINCABLES', 'NIFTY SMALLCAP 250', 'Finolex Cables Ltd.'),
    ('FSL', 'NIFTY SMALLCAP 250', 'Firstsource Solutions Ltd.'),
    ('FIVESTAR', 'NIFTY SMALLCAP 250', 'Five-Star Business Finance Ltd.'),
    ('FORCEMOT', 'NIFTY SMALLCAP 250', 'Force Motors Ltd.'),
    ('GABRIEL', 'NIFTY SMALLCAP 250', 'Gabriel India Ltd.'),
    ('GALLANTT', 'NIFTY SMALLCAP 250', 'Gallantt Ispat Ltd.'),
    ('GRSE', 'NIFTY SMALLCAP 250', 'Garden Reach Shipbuilders & Engineers Ltd.'),
    ('GILLETTE', 'NIFTY SMALLCAP 250', 'Gillette India Ltd.'),
    ('GLAND', 'NIFTY SMALLCAP 250', 'Gland Pharma Ltd.'),
    ('GODIGIT', 'NIFTY SMALLCAP 250', 'Go Digit General Insurance Ltd.'),
    ('GPIL', 'NIFTY SMALLCAP 250', 'Godawari Power & Ispat Ltd.'),
    ('GRANULES', 'NIFTY SMALLCAP 250', 'Granules India Ltd.'),
    ('GRAPHITE', 'NIFTY SMALLCAP 250', 'Graphite India Ltd.'),
    ('GRAVITA', 'NIFTY SMALLCAP 250', 'Gravita India Ltd.'),
    ('GESHIP', 'NIFTY SMALLCAP 250', 'Great Eastern Shipping Co. Ltd.'),
    ('GMDCLTD', 'NIFTY SMALLCAP 250', 'Gujarat Mineral Development Corporation Ltd.'),
    ('HEG', 'NIFTY SMALLCAP 250', 'H.E.G. Ltd.'),
    ('HBLENGINE', 'NIFTY SMALLCAP 250', 'HBL Engineering Ltd.'),
    ('HFCL', 'NIFTY SMALLCAP 250', 'HFCL Ltd.'),
    ('HSCL', 'NIFTY SMALLCAP 250', 'Himadri Speciality Chemical Ltd.'),
    ('HINDCOPPER', 'NIFTY SMALLCAP 250', 'Hindustan Copper Ltd.'),
    ('HOMEFIRST', 'NIFTY SMALLCAP 250', 'Home First Finance Company India Ltd.'),
    ('HONASA', 'NIFTY SMALLCAP 250', 'Honasa Consumer Ltd.'),
    ('IDBI', 'NIFTY SMALLCAP 250', 'IDBI Bank Ltd.'),
    ('IFCI', 'NIFTY SMALLCAP 250', 'IFCI Ltd.'),
    ('IIFL', 'NIFTY SMALLCAP 250', 'IIFL Finance Ltd.'),
    ('IRB', 'NIFTY SMALLCAP 250', 'IRB Infrastructure Developers Ltd.'),
    ('IRCON', 'NIFTY SMALLCAP 250', 'IRCON International Ltd.'),
    ('ITI', 'NIFTY SMALLCAP 250', 'ITI Ltd.'),
    ('INDGN', 'NIFTY SMALLCAP 250', 'Indegene Ltd.'),
    ('INDIACEM', 'NIFTY SMALLCAP 250', 'India Cements Ltd.'),
    ('INDIAMART', 'NIFTY SMALLCAP 250', 'Indiamart Intermesh Ltd.'),
    ('IEX', 'NIFTY SMALLCAP 250', 'Indian Energy Exchange Ltd.'),
    ('IOB', 'NIFTY SMALLCAP 250', 'Indian Overseas Bank'),
    ('IGL', 'NIFTY SMALLCAP 250', 'Indraprastha Gas Ltd.'),
    ('INOXWIND', 'NIFTY SMALLCAP 250', 'Inox Wind Ltd.'),
    ('INTELLECT', 'NIFTY SMALLCAP 250', 'Intellect Design Arena Ltd.'),
    ('IGIL', 'NIFTY SMALLCAP 250', 'International Gemological Institute Ltd.'),
    ('IKS', 'NIFTY SMALLCAP 250', 'Inventurus Knowledge Solutions Ltd.'),
    ('JBMA', 'NIFTY SMALLCAP 250', 'JBM Auto Ltd.'),
    ('JKTYRE', 'NIFTY SMALLCAP 250', 'JK Tyre & Industries Ltd.'),
    ('JMFINANCIL', 'NIFTY SMALLCAP 250', 'JM Financial Ltd.'),
    ('JSWCEMENT', 'NIFTY SMALLCAP 250', 'JSW Cement Ltd.'),
    ('JSWDULUX', 'NIFTY SMALLCAP 250', 'JSW Dulux Ltd.'),
    ('JAINREC', 'NIFTY SMALLCAP 250', 'Jain Resource Recycling Ltd.'),
    ('JPPOWER', 'NIFTY SMALLCAP 250', 'Jaiprakash Power Ventures Ltd.'),
    ('J&KBANK', 'NIFTY SMALLCAP 250', 'Jammu & Kashmir Bank Ltd.'),
    ('JINDALSAW', 'NIFTY SMALLCAP 250', 'Jindal Saw Ltd.'),
    ('JUBLINGREA', 'NIFTY SMALLCAP 250', 'Jubilant Ingrevia Ltd.'),
    ('JUBLPHARMA', 'NIFTY SMALLCAP 250', 'Jubilant Pharmova Ltd.'),
    ('JWL', 'NIFTY SMALLCAP 250', 'Jupiter Wagons Ltd.'),
    ('JYOTICNC', 'NIFTY SMALLCAP 250', 'Jyoti CNC Automation Ltd.'),
    ('KAJARIACER', 'NIFTY SMALLCAP 250', 'Kajaria Ceramics Ltd.'),
    ('KPIL', 'NIFTY SMALLCAP 250', 'Kalpataru Projects International Ltd.'),
    ('KARURVYSYA', 'NIFTY SMALLCAP 250', 'Karur Vysya Bank Ltd.'),
    ('KAYNES', 'NIFTY SMALLCAP 250', 'Kaynes Technology India Ltd.'),
    ('KEC', 'NIFTY SMALLCAP 250', 'Kec International Ltd.'),
    ('KFINTECH', 'NIFTY SMALLCAP 250', 'Kfin Technologies Ltd.'),
    ('KIRLOSENG', 'NIFTY SMALLCAP 250', 'Kirloskar Oil Eng Ltd.'),
    ('KIMS', 'NIFTY SMALLCAP 250', 'Krishna Institute of Medical Sciences Ltd.'),
    ('LTFOODS', 'NIFTY SMALLCAP 250', 'LT Foods Ltd.'),
    ('LATENTVIEW', 'NIFTY SMALLCAP 250', 'Latent View Analytics Ltd.'),
    ('THELEELA', 'NIFTY SMALLCAP 250', 'Leela Palaces Hotels & Resorts Ltd.'),
    ('LEMONTREE', 'NIFTY SMALLCAP 250', 'Lemon Tree Hotels Ltd.'),
    ('MMTC', 'NIFTY SMALLCAP 250', 'MMTC Ltd.'),
    ('MGL', 'NIFTY SMALLCAP 250', 'Mahanagar Gas Ltd.'),
    ('MANAPPURAM', 'NIFTY SMALLCAP 250', 'Manappuram Finance Ltd.'),
    ('MRPL', 'NIFTY SMALLCAP 250', 'Mangalore Refinery & Petrochemicals Ltd.'),
    ('MEESHO', 'NIFTY SMALLCAP 250', 'Meesho Ltd.'),
    ('MINDACORP', 'NIFTY SMALLCAP 250', 'Minda Corporation Ltd.'),
    ('MSUMI', 'NIFTY SMALLCAP 250', 'Motherson Sumi Wiring India Ltd.'),
    ('NATCOPHARM', 'NIFTY SMALLCAP 250', 'NATCO Pharma Ltd.'),
    ('NBCC', 'NIFTY SMALLCAP 250', 'NBCC (India) Ltd.'),
    ('NCC', 'NIFTY SMALLCAP 250', 'NCC Ltd.'),
    ('NSLNISP', 'NIFTY SMALLCAP 250', 'NMDC Steel Ltd.'),
    ('NH', 'NIFTY SMALLCAP 250', 'Narayana Hrudayalaya Ltd.'),
    ('NAVA', 'NIFTY SMALLCAP 250', 'Nava Ltd.'),
    ('NAVINFLUOR', 'NIFTY SMALLCAP 250', 'Navin Fluorine International Ltd.'),
    ('NETWEB', 'NIFTY SMALLCAP 250', 'Netweb Technologies India Ltd.'),
    ('NEULANDLAB', 'NIFTY SMALLCAP 250', 'Neuland Laboratories Ltd.'),
    ('NEWGEN', 'NIFTY SMALLCAP 250', 'Newgen Software Technologies Ltd.'),
    ('NIVABUPA', 'NIFTY SMALLCAP 250', 'Niva Bupa Health Insurance Company Ltd.'),
    ('NUVAMA', 'NIFTY SMALLCAP 250', 'Nuvama Wealth Management Ltd.'),
    ('NUVOCO', 'NIFTY SMALLCAP 250', 'Nuvoco Vistas Corporation Ltd.'),
    ('OLAELEC', 'NIFTY SMALLCAP 250', 'Ola Electric Mobility Ltd.'),
    ('OLECTRA', 'NIFTY SMALLCAP 250', 'Olectra Greentech Ltd.'),
    ('ONESOURCE', 'NIFTY SMALLCAP 250', 'Onesource Specialty Pharma Ltd.'),
    ('PCBL', 'NIFTY SMALLCAP 250', 'PCBL Chemical Ltd.'),
    ('PGEL', 'NIFTY SMALLCAP 250', 'PG Electroplast Ltd.'),
    ('PNBHOUSING', 'NIFTY SMALLCAP 250', 'PNB Housing Finance Ltd.'),
    ('PTCIL', 'NIFTY SMALLCAP 250', 'PTC Industries Ltd.'),
    ('PVRINOX', 'NIFTY SMALLCAP 250', 'PVR INOX Ltd.'),
    ('PARADEEP', 'NIFTY SMALLCAP 250', 'Paradeep Phosphates Ltd.'),
    ('PFIZER', 'NIFTY SMALLCAP 250', 'Pfizer Ltd.'),
    ('PWL', 'NIFTY SMALLCAP 250', 'Physicswallah Ltd.'),
    ('PINELABS', 'NIFTY SMALLCAP 250', 'Pine Labs Ltd.'),
    ('PIRAMALFIN', 'NIFTY SMALLCAP 250', 'Piramal Finance Ltd.'),
    ('PPLPHARMA', 'NIFTY SMALLCAP 250', 'Piramal Pharma Ltd.'),
    ('POLYMED', 'NIFTY SMALLCAP 250', 'Poly Medicure Ltd.'),
    ('POONAWALLA', 'NIFTY SMALLCAP 250', 'Poonawalla Fincorp Ltd.'),
    ('PFOCUS', 'NIFTY SMALLCAP 250', 'Prime Focus Ltd.'),
    ('RRKABEL', 'NIFTY SMALLCAP 250', 'R R Kabel Ltd.'),
    ('RBLBANK', 'NIFTY SMALLCAP 250', 'RBL Bank Ltd.'),
    ('RHIM', 'NIFTY SMALLCAP 250', 'RHI MAGNESITA INDIA LTD.'),
    ('RITES', 'NIFTY SMALLCAP 250', 'RITES Ltd.'),
    ('RAILTEL', 'NIFTY SMALLCAP 250', 'Railtel Corporation Of India Ltd.'),
    ('RAINBOW', 'NIFTY SMALLCAP 250', 'Rainbow Childrens Medicare Ltd.'),
    ('RKFORGE', 'NIFTY SMALLCAP 250', 'Ramkrishna Forgings Ltd.'),
    ('REDINGTON', 'NIFTY SMALLCAP 250', 'Redington Ltd.'),
    ('RPOWER', 'NIFTY SMALLCAP 250', 'Reliance Power Ltd.'),
    ('SBFC', 'NIFTY SMALLCAP 250', 'SBFC Finance Ltd.'),
    ('SAGILITY', 'NIFTY SMALLCAP 250', 'Sagility Ltd.'),
    ('SAILIFE', 'NIFTY SMALLCAP 250', 'Sai Life Sciences Ltd.'),
    ('SAMMAANCAP', 'NIFTY SMALLCAP 250', 'Sammaan Capital Ltd.'),
    ('SAPPHIRE', 'NIFTY SMALLCAP 250', 'Sapphire Foods India Ltd.'),
    ('SARDAEN', 'NIFTY SMALLCAP 250', 'Sarda Energy and Minerals Ltd.'),
    ('SAREGAMA', 'NIFTY SMALLCAP 250', 'Saregama India Ltd'),
    ('SCHNEIDER', 'NIFTY SMALLCAP 250', 'Schneider Electric Infrastructure Ltd.'),
    ('SCI', 'NIFTY SMALLCAP 250', 'Shipping Corporation of India Ltd.'),
    ('SHYAMMETL', 'NIFTY SMALLCAP 250', 'Shyam Metalics and Energy Ltd.'),
    ('SIGNATURE', 'NIFTY SMALLCAP 250', 'Signatureglobal (India) Ltd.'),
    ('SOBHA', 'NIFTY SMALLCAP 250', 'Sobha Ltd.'),
    ('SONACOMS', 'NIFTY SMALLCAP 250', 'Sona BLW Precision Forgings Ltd.'),
    ('SONATSOFTW', 'NIFTY SMALLCAP 250', 'Sonata Software Ltd.'),
    ('STARHEALTH', 'NIFTY SMALLCAP 250', 'Star Health and Allied Insurance Company Ltd.'),
    ('SUMICHEM', 'NIFTY SMALLCAP 250', 'Sumitomo Chemical India Ltd.'),
    ('SUNTV', 'NIFTY SMALLCAP 250', 'Sun TV Network Ltd.'),
    ('SPLPETRO', 'NIFTY SMALLCAP 250', 'Supreme Petrochem Ltd.'),
    ('SWANCORP', 'NIFTY SMALLCAP 250', 'Swan Corp Ltd.'),
    ('SYNGENE', 'NIFTY SMALLCAP 250', 'Syngene International Ltd.'),
    ('SYRMA', 'NIFTY SMALLCAP 250', 'Syrma SGS Technology Ltd.'),
    ('TBOTEK', 'NIFTY SMALLCAP 250', 'TBO Tek Ltd.'),
    ('TATACHEM', 'NIFTY SMALLCAP 250', 'Tata Chemicals Ltd.'),
    ('TATATECH', 'NIFTY SMALLCAP 250', 'Tata Technologies Ltd.'),
    ('TTML', 'NIFTY SMALLCAP 250', 'Tata Teleservices (Maharashtra) Ltd.'),
    ('TECHNOE', 'NIFTY SMALLCAP 250', 'Techno Electric & Engineering Company Ltd.'),
    ('TEGA', 'NIFTY SMALLCAP 250', 'Tega Industries Ltd.'),
    ('TEJASNET', 'NIFTY SMALLCAP 250', 'Tejas Networks Ltd.'),
    ('TENNIND', 'NIFTY SMALLCAP 250', 'Tenneco Clean Air India Ltd.'),
    ('RAMCOCEM', 'NIFTY SMALLCAP 250', 'The Ramco Cements Ltd.'),
    ('TIMKEN', 'NIFTY SMALLCAP 250', 'Timken India Ltd.'),
    ('TITAGARH', 'NIFTY SMALLCAP 250', 'Titagarh Rail Systems Ltd.'),
    ('TARIL', 'NIFTY SMALLCAP 250', 'Transformers And Rectifiers (India) Ltd.'),
    ('TRAVELFOOD', 'NIFTY SMALLCAP 250', 'Travel Food Services Ltd.'),
    ('TRIDENT', 'NIFTY SMALLCAP 250', 'Trident Ltd.'),
    ('TRITURBINE', 'NIFTY SMALLCAP 250', 'Triveni Turbine Ltd.'),
    ('UCOBANK', 'NIFTY SMALLCAP 250', 'UCO Bank'),
    ('UTIAMC', 'NIFTY SMALLCAP 250', 'UTI Asset Management Company Ltd.'),
    ('URBANCO', 'NIFTY SMALLCAP 250', 'Urban Company Ltd.'),
    ('USHAMART', 'NIFTY SMALLCAP 250', 'Usha Martin Ltd.'),
    ('VTL', 'NIFTY SMALLCAP 250', 'Vardhman Textiles Ltd.'),
    ('VIJAYA', 'NIFTY SMALLCAP 250', 'Vijaya Diagnostic Centre Ltd.'),
    ('WELCORP', 'NIFTY SMALLCAP 250', 'Welspun Corp Ltd.'),
    ('WELSPUNLIV', 'NIFTY SMALLCAP 250', 'Welspun Living Ltd.'),
    ('WHIRLPOOL', 'NIFTY SMALLCAP 250', 'Whirlpool of India Ltd.'),
    ('WOCKPHARMA', 'NIFTY SMALLCAP 250', 'Wockhardt Ltd.'),
    ('ZFCVINDIA', 'NIFTY SMALLCAP 250', 'ZF Commercial Vehicle Control Systems India Ltd.'),
    ('ZEEL', 'NIFTY SMALLCAP 250', 'Zee Entertainment Enterprises Ltd.'),
    ('ZENTEC', 'NIFTY SMALLCAP 250', 'Zen Technologies Ltd.'),
    ('ZENSARTECH', 'NIFTY SMALLCAP 250', 'Zensar Technolgies Ltd.'),
    ('ZYDUSWELL', 'NIFTY SMALLCAP 250', 'Zydus Wellness Ltd.'),
    ('ECLERX', 'NIFTY SMALLCAP 250', 'eClerx Services Ltd.'),
    ('ASKAUTOLTD', 'NIFTY MICROCAP 250', 'ASK Automotive Ltd.'),
    ('AXISCADES', 'NIFTY MICROCAP 250', 'AXISCADES Technologies Ltd.'),
    ('AARTIDRUGS', 'NIFTY MICROCAP 250', 'Aarti Drugs Ltd.'),
    ('AARTIPHARM', 'NIFTY MICROCAP 250', 'Aarti Pharmalabs Ltd.'),
    ('AVL', 'NIFTY MICROCAP 250', 'Aditya Vision Ltd.'),
    ('ADVENZYMES', 'NIFTY MICROCAP 250', 'Advanced Enzyme Tech Ltd.'),
    ('AEQUS', 'NIFTY MICROCAP 250', 'Aequs Ltd.'),
    ('AETHER', 'NIFTY MICROCAP 250', 'Aether Industries Ltd.'),
    ('AHLUCONT', 'NIFTY MICROCAP 250', 'Ahluwalia Contracts (India) Ltd.'),
    ('AKUMS', 'NIFTY MICROCAP 250', 'Akums Drugs and Pharmaceuticals Ltd.'),
    ('APLLTD', 'NIFTY MICROCAP 250', 'Alembic Pharmaceuticals Ltd.'),
    ('ALIVUS', 'NIFTY MICROCAP 250', 'Alivus Life Sciences Ltd.'),
    ('ALKYLAMINE', 'NIFTY MICROCAP 250', 'Alkyl Amines Chemicals Ltd.'),
    ('ALOKINDS', 'NIFTY MICROCAP 250', 'Alok Industries Ltd.'),
    ('APOLLO', 'NIFTY MICROCAP 250', 'Apollo Micro Systems Ltd.'),
    ('ACI', 'NIFTY MICROCAP 250', 'Archean Chemical Industries Ltd.'),
    ('ARVINDFASN', 'NIFTY MICROCAP 250', 'Arvind Fashions Ltd.'),
    ('ARVIND', 'NIFTY MICROCAP 250', 'Arvind Ltd.'),
    ('ASHAPURMIN', 'NIFTY MICROCAP 250', 'Ashapura Minechem Ltd.'),
    ('ASHOKA', 'NIFTY MICROCAP 250', 'Ashoka Buildcon Ltd.'),
    ('ASTRAMICRO', 'NIFTY MICROCAP 250', 'Astra Microwave Products Ltd.'),
    ('ATLANTAELE', 'NIFTY MICROCAP 250', 'Atlanta Electricals Ltd.'),
    ('AURIONPRO', 'NIFTY MICROCAP 250', 'Aurionpro Solution Ltd.'),
    ('AVALON', 'NIFTY MICROCAP 250', 'Avalon Technologies Ltd.'),
    ('AVANTIFEED', 'NIFTY MICROCAP 250', 'Avanti Feeds Ltd.'),
    ('CCAVENUE', 'NIFTY MICROCAP 250', 'AvenuesAI Ltd.'),
    ('AWFIS', 'NIFTY MICROCAP 250', 'Awfis Space Solutions Ltd.'),
    ('AZAD', 'NIFTY MICROCAP 250', 'Azad Engineering Ltd.'),
    ('BAJAJELEC', 'NIFTY MICROCAP 250', 'Bajaj Electricals Ltd'),
    ('BALAMINES', 'NIFTY MICROCAP 250', 'Balaji Amines Ltd.'),
    ('BALUFORGE', 'NIFTY MICROCAP 250', 'Balu Forge Industries Ltd.'),
    ('BANCOINDIA', 'NIFTY MICROCAP 250', 'Banco Products (India) Ltd.'),
    ('BIRLACORPN', 'NIFTY MICROCAP 250', 'Birla Corporation Ltd.'),
    ('BBOX', 'NIFTY MICROCAP 250', 'Black Box Ltd.'),
    ('BLACKBUCK', 'NIFTY MICROCAP 250', 'Blackbuck Ltd.'),
    ('BLUESTONE', 'NIFTY MICROCAP 250', 'BlueStone Jewellery and Lifestyle Ltd.'),
    ('BORORENEW', 'NIFTY MICROCAP 250', 'Borosil Renewables Ltd.'),
    ('CMSINFO', 'NIFTY MICROCAP 250', 'CMS Info Systems Ltd.'),
    ('CORONA', 'NIFTY MICROCAP 250', 'CORONA Remedies Ltd.'),
    ('CSBBANK', 'NIFTY MICROCAP 250', 'CSB Bank Ltd.'),
    ('CAMPUS', 'NIFTY MICROCAP 250', 'Campus Activewear Ltd.'),
    ('CRAMC', 'NIFTY MICROCAP 250', 'Canara Robeco Asset Management Company Ltd.'),
    ('CAPILLARY', 'NIFTY MICROCAP 250', 'Capillary Technologies India Ltd.'),
    ('CELLO', 'NIFTY MICROCAP 250', 'Cello World Ltd.'),
    ('CENTURYPLY', 'NIFTY MICROCAP 250', 'Century Plyboards (India) Ltd.'),
    ('CERA', 'NIFTY MICROCAP 250', 'Cera Sanitaryware Ltd'),
    ('CRIZAC', 'NIFTY MICROCAP 250', 'Crizac Ltd.'),
    ('CUPID', 'NIFTY MICROCAP 250', 'Cupid Ltd.'),
    ('DCBBANK', 'NIFTY MICROCAP 250', 'DCB Bank Ltd.'),
    ('DATAMATICS', 'NIFTY MICROCAP 250', 'Datamatics Global Services Ltd.'),
    ('DIACABS', 'NIFTY MICROCAP 250', 'Diamond Power Infrastructure Ltd.'),
    ('DBL', 'NIFTY MICROCAP 250', 'Dilip Buildcon Ltd.'),
    ('AGARWALEYE', 'NIFTY MICROCAP 250', 'Dr. Agarwal''s Health Care Ltd.'),
    ('DUMMYINGL1', 'NIFTY MICROCAP 250', 'Dummy India Glycols ltd. 1'),
    ('DUMMYINGL2', 'NIFTY MICROCAP 250', 'Dummy India Glycols ltd. 2'),
    ('DUMMYINXGN', 'NIFTY MICROCAP 250', 'Dummy Inox Green Ltd.'),
    ('DUMMYTRVN', 'NIFTY MICROCAP 250', 'Dummy Triveni Ltd.'),
    ('DYNAMATECH', 'NIFTY MICROCAP 250', 'Dynamatic Technologies Ltd.'),
    ('EPL', 'NIFTY MICROCAP 250', 'EPL Ltd.'),
    ('EDELWEISS', 'NIFTY MICROCAP 250', 'Edelweiss Financial Services Ltd.'),
    ('EMIL', 'NIFTY MICROCAP 250', 'Electronics Mart India Ltd.'),
    ('ELECTCAST', 'NIFTY MICROCAP 250', 'Electrosteel Castings Ltd.'),
    ('ELLEN', 'NIFTY MICROCAP 250', 'Ellenbarrie Industrial Gases Ltd.'),
    ('EMBDL', 'NIFTY MICROCAP 250', 'Embassy Developments Ltd.'),
    ('ENTERO', 'NIFTY MICROCAP 250', 'Entero Healthcare Solutions Ltd.'),
    ('EIEL', 'NIFTY MICROCAP 250', 'Enviro Infra Engineers Ltd.'),
    ('EQUITASBNK', 'NIFTY MICROCAP 250', 'Equitas Small Finance Bank Ltd.'),
    ('ETHOSLTD', 'NIFTY MICROCAP 250', 'Ethos Ltd.'),
    ('EUREKAFORB', 'NIFTY MICROCAP 250', 'Eureka Forbes Ltd.'),
    ('FEDFINA', 'NIFTY MICROCAP 250', 'Fedbank Financial Services Ltd.'),
    ('FIEMIND', 'NIFTY MICROCAP 250', 'Fiem Industries Ltd'),
    ('FINPIPE', 'NIFTY MICROCAP 250', 'Finolex Industries Ltd.'),
    ('UTLSOLAR', 'NIFTY MICROCAP 250', 'Fujiyama Power Systems Ltd.'),
    ('GHCL', 'NIFTY MICROCAP 250', 'GHCL Ltd.'),
    ('GMMPFAUDLR', 'NIFTY MICROCAP 250', 'GMM Pfaudler Ltd.'),
    ('GMRP&UI', 'NIFTY MICROCAP 250', 'GMR Power and Urban Infra Ltd.'),
    ('GRWRHITECH', 'NIFTY MICROCAP 250', 'Garware Hi-Tech Films Ltd.'),
    ('GODREJAGRO', 'NIFTY MICROCAP 250', 'Godrej Agrovet Ltd.'),
    ('GOKEX', 'NIFTY MICROCAP 250', 'Gokaldas Exports Ltd.'),
    ('GOKULAGRO', 'NIFTY MICROCAP 250', 'Gokul Agro Resources Ltd.'),
    ('GREAVESCOT', 'NIFTY MICROCAP 250', 'Greaves Cotton Ltd.'),
    ('GRINDWELL', 'NIFTY MICROCAP 250', 'Grindwell Norton Ltd.'),
    ('GAEL', 'NIFTY MICROCAP 250', 'Gujarat Ambuja Exports Ltd.'),
    ('GNFC', 'NIFTY MICROCAP 250', 'Gujarat Narmada Valley Fertilizers and Chemicals Ltd.'),
    ('GPPL', 'NIFTY MICROCAP 250', 'Gujarat Pipavav Port Ltd.'),
    ('GSFC', 'NIFTY MICROCAP 250', 'Gujarat State Fertilizers & Chemicals Ltd.'),
    ('HGINFRA', 'NIFTY MICROCAP 250', 'H.G. Infra Engineering Ltd.'),
    ('HAPPSTMNDS', 'NIFTY MICROCAP 250', 'Happiest Minds Technologies Ltd.'),
    ('HCG', 'NIFTY MICROCAP 250', 'Healthcare Global Enterprises Ltd.'),
    ('HEMIPROP', 'NIFTY MICROCAP 250', 'Hemisphere Properties India Ltd.'),
    ('HERITGFOOD', 'NIFTY MICROCAP 250', 'Heritage Foods Ltd.'),
    ('HCC', 'NIFTY MICROCAP 250', 'Hindustan Construction Co. Ltd.'),
    ('IFBIND', 'NIFTY MICROCAP 250', 'IFB Industries Ltd.'),
    ('IIFLCAPS', 'NIFTY MICROCAP 250', 'IIFL Capital Services Ltd.'),
    ('INOXINDIA', 'NIFTY MICROCAP 250', 'INOX India Ltd.'),
    ('INDIAGLYCO', 'NIFTY MICROCAP 250', 'India Glycols Ltd.'),
    ('INDIASHLTR', 'NIFTY MICROCAP 250', 'India Shelter Finance Corporation Ltd.'),
    ('IMFA', 'NIFTY MICROCAP 250', 'Indian Metals & Ferro Alloys Ltd.'),
    ('INDIGOPNTS', 'NIFTY MICROCAP 250', 'Indigo Paints Ltd.'),
    ('ICIL', 'NIFTY MICROCAP 250', 'Indo Count Industries Ltd.'),
    ('INOXGREEN', 'NIFTY MICROCAP 250', 'Inox Green Energy Services Ltd.'),
    ('IONEXCHANG', 'NIFTY MICROCAP 250', 'Ion Exchange (India) Ltd.'),
    ('JAIBALAJI', 'NIFTY MICROCAP 250', 'JAI BALAJI INDUSTRIES Ltd.'),
    ('JKLAKSHMI', 'NIFTY MICROCAP 250', 'JK Lakshmi Cement Ltd.'),
    ('JKPAPER', 'NIFTY MICROCAP 250', 'JK Paper Ltd.'),
    ('JAMNAAUTO', 'NIFTY MICROCAP 250', 'Jamna Auto Industries Ltd.'),
    ('JSFB', 'NIFTY MICROCAP 250', 'Jana Small Finance Bank Ltd.'),
    ('JAYNECOIND', 'NIFTY MICROCAP 250', 'Jayaswal Neco Industries Ltd.'),
    ('JSLL', 'NIFTY MICROCAP 250', 'Jeena Sikho Lifecare Ltd.'),
    ('JLHL', 'NIFTY MICROCAP 250', 'Jupiter Life Line Hospitals Ltd.'),
    ('JUSTDIAL', 'NIFTY MICROCAP 250', 'Justdial Ltd.'),
    ('JYOTHYLAB', 'NIFTY MICROCAP 250', 'Jyothy Labs Ltd.'),
    ('KNRCON', 'NIFTY MICROCAP 250', 'KNR Constructions Ltd.'),
    ('KPIGREEN', 'NIFTY MICROCAP 250', 'KPI Green Energy Ltd.'),
    ('KRBL', 'NIFTY MICROCAP 250', 'KRBL Ltd.'),
    ('KRN', 'NIFTY MICROCAP 250', 'KRN HEAT EXCHANGER AND REFRIGERATION Ltd.'),
    ('KSB', 'NIFTY MICROCAP 250', 'KSB Ltd.'),
    ('KANSAINER', 'NIFTY MICROCAP 250', 'Kansai Nerolac Paints Ltd.'),
    ('KTKBANK', 'NIFTY MICROCAP 250', 'Karnataka Bank Ltd.'),
    ('KSCL', 'NIFTY MICROCAP 250', 'Kaveri Seed Company Ltd.'),
    ('KIRLOSBROS', 'NIFTY MICROCAP 250', 'Kirloskar Brothers Ltd.'),
    ('KIRLPNU', 'NIFTY MICROCAP 250', 'Kirloskar Pneumatic Company Ltd.'),
    ('KITEX', 'NIFTY MICROCAP 250', 'Kitex Garments Ltd.'),
    ('LXCHEM', 'NIFTY MICROCAP 250', 'Laxmi Organic Industries Ltd.'),
    ('IXIGO', 'NIFTY MICROCAP 250', 'Le Travenues Technology Ltd.'),
    ('LLOYDSENGG', 'NIFTY MICROCAP 250', 'Lloyds Engineering Works Ltd.'),
    ('LLOYDSENT', 'NIFTY MICROCAP 250', 'Lloyds Enterprises Ltd.'),
    ('LUMAXTECH', 'NIFTY MICROCAP 250', 'Lumax Auto Technologies Ltd.'),
    ('MOIL', 'NIFTY MICROCAP 250', 'MOIL Ltd.'),
    ('MSTCLTD', 'NIFTY MICROCAP 250', 'MSTC Ltd.'),
    ('MTARTECH', 'NIFTY MICROCAP 250', 'MTAR Technologies Ltd.'),
    ('MAHSCOOTER', 'NIFTY MICROCAP 250', 'Maharashtra Scooters Ltd.'),
    ('MAHSEAMLES', 'NIFTY MICROCAP 250', 'Maharashtra Seamless Ltd.'),
    ('MANORAMA', 'NIFTY MICROCAP 250', 'Manorama Industries Ltd.'),
    ('MARKSANS', 'NIFTY MICROCAP 250', 'Marksans Pharma Ltd.'),
    ('MASTEK', 'NIFTY MICROCAP 250', 'Mastek Ltd.'),
    ('MEDPLUS', 'NIFTY MICROCAP 250', 'Medplus Health Services Ltd.'),
    ('METROPOLIS', 'NIFTY MICROCAP 250', 'Metropolis Healthcare Ltd.'),
    ('MIDHANI', 'NIFTY MICROCAP 250', 'Mishra Dhatu Nigam Ltd.'),
    ('BECTORFOOD', 'NIFTY MICROCAP 250', 'Mrs. Bectors Food Specialities Ltd.'),
    ('NEOGEN', 'NIFTY MICROCAP 250', 'NEOGEN CHEMICALS LTD.'),
    ('NESCO', 'NIFTY MICROCAP 250', 'NESCO Ltd.'),
    ('NFL', 'NIFTY MICROCAP 250', 'National Fertilizers Ltd.'),
    ('NAZARA', 'NIFTY MICROCAP 250', 'Nazara Technologies Ltd.'),
    ('NETWORK18', 'NIFTY MICROCAP 250', 'Network18 Media & Investments Ltd.'),
    ('OPTIEMUS', 'NIFTY MICROCAP 250', 'Optiemus Infracom Ltd.'),
    ('ORIENTCEM', 'NIFTY MICROCAP 250', 'Orient Cement Ltd.'),
    ('ORKLAINDIA', 'NIFTY MICROCAP 250', 'Orkla India Ltd.'),
    ('OSWALPUMPS', 'NIFTY MICROCAP 250', 'Oswal Pumps Ltd.'),
    ('PNGJL', 'NIFTY MICROCAP 250', 'P N Gadgil Jewellers Ltd.'),
    ('PCJEWELLER', 'NIFTY MICROCAP 250', 'PC Jeweller Ltd.'),
    ('PNCINFRA', 'NIFTY MICROCAP 250', 'PNC Infratech Ltd.'),
    ('PTC', 'NIFTY MICROCAP 250', 'PTC India Ltd.'),
    ('PARAS', 'NIFTY MICROCAP 250', 'Paras Defence and Space Technologies Ltd.'),
    ('PARKHOSPS', 'NIFTY MICROCAP 250', 'Park Medi World Ltd.'),
    ('PGIL', 'NIFTY MICROCAP 250', 'Pearl Global Industries Ltd.'),
    ('PICCADIL', 'NIFTY MICROCAP 250', 'Piccadily Agro Industries Ltd.'),
    ('POWERMECH', 'NIFTY MICROCAP 250', 'Power Mech Projects Ltd.'),
    ('PRAJIND', 'NIFTY MICROCAP 250', 'Praj Industries Ltd.'),
    ('PRICOLLTD', 'NIFTY MICROCAP 250', 'Pricol Ltd.'),
    ('PRSMJOHNSN', 'NIFTY MICROCAP 250', 'Prism Johnson Ltd.'),
    ('PRIVISCL', 'NIFTY MICROCAP 250', 'Privi Speciality Chemicals Ltd.'),
    ('PRUDENT', 'NIFTY MICROCAP 250', 'Prudent Corporate Advisory Services Ltd.'),
    ('PURVA', 'NIFTY MICROCAP 250', 'Puravankara Ltd.'),
    ('QPOWER', 'NIFTY MICROCAP 250', 'QUALITY POWER ELECTRICAL EQUIPMENTS Ltd.'),
    ('QUESS', 'NIFTY MICROCAP 250', 'Quess Corp Ltd.'),
    ('RAIN', 'NIFTY MICROCAP 250', 'Rain Industries Ltd'),
    ('RALLIS', 'NIFTY MICROCAP 250', 'Rallis India Ltd.'),
    ('RCF', 'NIFTY MICROCAP 250', 'Rashtriya Chemicals & Fertilizers Ltd.'),
    ('RATEGAIN', 'NIFTY MICROCAP 250', 'Rategain Travel Technologies Ltd.'),
    ('RATNAMANI', 'NIFTY MICROCAP 250', 'Ratnamani Metals & Tubes Ltd.'),
    ('RTNINDIA', 'NIFTY MICROCAP 250', 'RattanIndia Enterprises Ltd.'),
    ('RTNPOWER', 'NIFTY MICROCAP 250', 'RattanIndia Power Ltd.'),
    ('RAYMONDLSL', 'NIFTY MICROCAP 250', 'Raymond Lifestyle Ltd.'),
    ('REDTAPE', 'NIFTY MICROCAP 250', 'Redtape Ltd.'),
    ('REFEX', 'NIFTY MICROCAP 250', 'Refex Industries Ltd.'),
    ('RELAXO', 'NIFTY MICROCAP 250', 'Relaxo Footwears Ltd.'),
    ('RELIGARE', 'NIFTY MICROCAP 250', 'Religare Enterprises Ltd.'),
    ('RBA', 'NIFTY MICROCAP 250', 'Restaurant Brands Asia Ltd.'),
    ('ROUTE', 'NIFTY MICROCAP 250', 'Route Mobile Ltd.'),
    ('RUBICON', 'NIFTY MICROCAP 250', 'Rubicon Research Ltd.'),
    ('SKFINDUS', 'NIFTY MICROCAP 250', 'SKF India (Industrial) Ltd.'),
    ('SKFINDIA', 'NIFTY MICROCAP 250', 'SKF India Ltd.'),
    ('SKYGOLD', 'NIFTY MICROCAP 250', 'SKY GOLD AND DIAMONDS Ltd.'),
    ('SMLMAH', 'NIFTY MICROCAP 250', 'SML Mahindra Ltd.'),
    ('SHRIPISTON', 'NIFTY MICROCAP 250', 'SPR Auto Technologies Ltd.'),
    ('LOTUSDEV', 'NIFTY MICROCAP 250', 'SRI LOTUS DEVELOPERS AND REALTY Ltd.'),
    ('SAATVIKGL', 'NIFTY MICROCAP 250', 'Saatvik Green Energy Ltd.'),
    ('SAFARI', 'NIFTY MICROCAP 250', 'Safari Industries (India) Ltd.'),
    ('SAMHI', 'NIFTY MICROCAP 250', 'Samhi Hotels Ltd.'),
    ('SANDUMA', 'NIFTY MICROCAP 250', 'Sandur Manganese & Iron Ores Ltd.'),
    ('SANOFICONR', 'NIFTY MICROCAP 250', 'Sanofi Consumer Healthcare India Ltd.'),
    ('SANSERA', 'NIFTY MICROCAP 250', 'Sansera Engineering Ltd.'),
    ('SENCO', 'NIFTY MICROCAP 250', 'Senco Gold Ltd.'),
    ('STYL', 'NIFTY MICROCAP 250', 'Seshaasai Technologies Ltd.'),
    ('SHAILY', 'NIFTY MICROCAP 250', 'Shaily Engineering Plastics Ltd.'),
    ('SHAKTIPUMP', 'NIFTY MICROCAP 250', 'Shakti Pumps (India) Ltd.'),
    ('SHARDACROP', 'NIFTY MICROCAP 250', 'Sharda Cropchem Ltd.'),
    ('SHAREINDIA', 'NIFTY MICROCAP 250', 'Share India Securities Ltd.'),
    ('SFL', 'NIFTY MICROCAP 250', 'Sheela Foam Ltd.'),
    ('SHILPAMED', 'NIFTY MICROCAP 250', 'Shilpa Medicare Ltd.'),
    ('RENUKA', 'NIFTY MICROCAP 250', 'Shree Renuka Sugars Ltd.'),
    ('SKIPPER', 'NIFTY MICROCAP 250', 'Skipper Ltd.'),
    ('SMARTWORKS', 'NIFTY MICROCAP 250', 'Smartworks Coworking Spaces Ltd.'),
    ('SOUTHBANK', 'NIFTY MICROCAP 250', 'South Indian Bank Ltd.'),
    ('STARCEMENT', 'NIFTY MICROCAP 250', 'Star Cement Ltd.'),
    ('SWSOLAR', 'NIFTY MICROCAP 250', 'Sterling and Wilson Renewable Energy Ltd.'),
    ('STLTECH', 'NIFTY MICROCAP 250', 'Sterlite Technologies Ltd.'),
    ('STAR', 'NIFTY MICROCAP 250', 'Strides Pharma Science Ltd.'),
    ('STYRENIX', 'NIFTY MICROCAP 250', 'Styrenix Performance Materials Ltd.'),
    ('SUBROS', 'NIFTY MICROCAP 250', 'Subros Ltd.'),
    ('SUDARSCHEM', 'NIFTY MICROCAP 250', 'Sudarshan Chemical Industries Ltd.'),
    ('SUDEEPPHRM', 'NIFTY MICROCAP 250', 'Sudeep Pharma Ltd.'),
    ('SPARC', 'NIFTY MICROCAP 250', 'Sun Pharma Advanced Research Company Ltd.'),
    ('SUNTECK', 'NIFTY MICROCAP 250', 'Sunteck Realty Ltd.'),
    ('SUPRIYA', 'NIFTY MICROCAP 250', 'Supriya Lifescience Ltd.'),
    ('SURYAROSNI', 'NIFTY MICROCAP 250', 'Surya Roshni Ltd.'),
    ('TARC', 'NIFTY MICROCAP 250', 'TARC Ltd.'),
    ('TDPOWERSYS', 'NIFTY MICROCAP 250', 'TD Power Systems Ltd.'),
    ('TSFINV', 'NIFTY MICROCAP 250', 'TSF Investments Ltd.'),
    ('TVSSCS', 'NIFTY MICROCAP 250', 'TVS Supply Chain Solutions Ltd.'),
    ('TMB', 'NIFTY MICROCAP 250', 'Tamilnad Mercantile Bank Ltd.'),
    ('TANLA', 'NIFTY MICROCAP 250', 'Tanla Platforms Ltd.'),
    ('TEXRAIL', 'NIFTY MICROCAP 250', 'Texmaco Rail & Eng. Ltd.'),
    ('THANGAMAYL', 'NIFTY MICROCAP 250', 'Thangamayil Jewellery Ltd.'),
    ('ANUP', 'NIFTY MICROCAP 250', 'The Anup Engineering Ltd.'),
    ('THOMASCOOK', 'NIFTY MICROCAP 250', 'Thomas Cook (India) Ltd.'),
    ('THYROCARE', 'NIFTY MICROCAP 250', 'Thyrocare Technologies Ltd.'),
    ('TI', 'NIFTY MICROCAP 250', 'Tilaknagar Industries Ltd.'),
    ('TIMETECHNO', 'NIFTY MICROCAP 250', 'Time Technoplast Ltd.'),
    ('TIPSMUSIC', 'NIFTY MICROCAP 250', 'Tips Music Ltd.'),
    ('TRANSRAILL', 'NIFTY MICROCAP 250', 'Transrail Lighting Ltd.'),
    ('TRIVENI', 'NIFTY MICROCAP 250', 'Triveni Engineering & Industries Ltd.'),
    ('UJJIVANSFB', 'NIFTY MICROCAP 250', 'Ujjivan Small Finance Bank Ltd.'),
    ('VGUARD', 'NIFTY MICROCAP 250', 'V-Guard Industries Ltd.'),
    ('VMART', 'NIFTY MICROCAP 250', 'V-Mart Retail Ltd.'),
    ('VIPIND', 'NIFTY MICROCAP 250', 'V.I.P. Industries Ltd.'),
    ('V2RETAIL', 'NIFTY MICROCAP 250', 'V2 Retail Ltd.'),
    ('DBREALTY', 'NIFTY MICROCAP 250', 'VALOR ESTATE Ltd.'),
    ('WABAG', 'NIFTY MICROCAP 250', 'Va Tech Wabag Ltd.'),
    ('VAIBHAVGBL', 'NIFTY MICROCAP 250', 'Vaibhav Global Ltd.'),
    ('VARROC', 'NIFTY MICROCAP 250', 'Varroc Engineering Ltd.'),
    ('MANYAVAR', 'NIFTY MICROCAP 250', 'Vedant Fashions Ltd.'),
    ('VIKRAMSOLR', 'NIFTY MICROCAP 250', 'Vikram Solar Ltd.'),
    ('VIYASH', 'NIFTY MICROCAP 250', 'Viyash Scientific Ltd.'),
    ('VOLTAMP', 'NIFTY MICROCAP 250', 'Voltamp Transformers Ltd'),
    ('WAAREERTL', 'NIFTY MICROCAP 250', 'Waaree Renewable Technologies Ltd.'),
    ('WAKEFIT', 'NIFTY MICROCAP 250', 'Wakefit Innovations Ltd.'),
    ('WEWORK', 'NIFTY MICROCAP 250', 'WeWork India Management Ltd.'),
    ('WEBELSOLAR', 'NIFTY MICROCAP 250', 'Websol Energy System Ltd.'),
    ('WELENT', 'NIFTY MICROCAP 250', 'Welspun Enterprises Ltd.'),
    ('WESTLIFE', 'NIFTY MICROCAP 250', 'Westlife Foodworld Ltd.'),
    ('YATHARTH', 'NIFTY MICROCAP 250', 'Yatharth Hospital & Trauma Care Services Ltd.'),
    ('ZAGGLE', 'NIFTY MICROCAP 250', 'Zaggle Prepaid Ocean Services Ltd.')
ON CONFLICT (ticker) DO NOTHING;
